name: Publish to JSR

on:
  workflow_dispatch:
  release:
    types: [published]
  push:
    tags:
      - "v*"
      - "mcp-kit-core@*"

concurrency:
  group: jsr-publish
  cancel-in-progress: false

jobs:
  publish:
    name: Publish package to JSR
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Verify package (dry run)
        run: deno publish --dry-run

      - name: Publish to JSR (requires repo linked in JSR settings)
        run: deno publish

